Improve installed profile handling

diff --git a/install b/install
--- a/install
+++ b/install
@@ -47,6 +47,43 @@ readarray -t PROFILE_FULL < <(sort_uniq_args "${PROFILE_FULL[@]}")
 
 assert_eq "${PROFILE_FULL[*]}" "${AVAILABLE_MODULES[*]}"
 
+list_installed_profiles() {
+    list_installed_modules | sed -n 's/^%//p'
+}
+
+show_default_profile() {
+    if [[ "${REMOTE_CONTAINERS:-}" == true ]]; then
+        echo "devcontainer"
+    else
+        echo "default"
+    fi
+}
+
+expand_profile() {
+    while [[ $# -gt 0 ]]; do
+        local module="$1"
+        shift
+        case "${module}" in
+        %devcontainer)
+            printf "%s\n" "${PROFILE_DEVCONTAINER[@]}"
+            ;;
+        %default)
+            printf "%s\n" "${PROFILE_DEFAULT[@]}"
+            ;;
+        %full)
+            printf "%s\n" "${PROFILE_FULL[@]}"
+            ;;
+        %*)
+            error "Unknown profile: ${module:1}"
+            return 1
+            ;;
+        *)
+            printf "%s\n" "${module}"
+            ;;
+        esac
+    done
+}
+
 install_main() {
     if [[ "${FLG_LIST_MODULES}" -eq 1 ]]; then
         for module in "${AVAILABLE_MODULES[@]}"; do
@@ -62,65 +99,113 @@ install_main() {
         return 0
     fi
 
-    # install modules specified by arguments
+    local -a profiles=()
     local -a install_modules=("$@")
+    local -a update_modules=()
 
     # if profile is specified, install modules specified by the profile
-    case "${OPT_PROFILE}" in
-    devcontainer)
-        install_modules+=("${PROFILE_DEVCONTAINER[@]}")
-        ;;
-    default)
-        install_modules+=("${PROFILE_DEFAULT[@]}")
-        ;;
-    full)
-        install_modules+=("${PROFILE_FULL[@]}")
-        ;;
-    none)
-        install_modules+=()
-        ;;
-    "")
-        if [[ "${#install_modules[@]}" -gt 0 ]]; then
-            # if modules are specified, install only them
-            :
-        elif [[ "${#INSTALLED_MODULES[@]}" -gt 0 ]]; then
-            # if no modules are specified, and some modules are installed, re-install them
-            info "Update installed modules"
-            install_modules=("${INSTALLED_MODULES[@]}")
-        else
-            # if no modules are specified, and no modules are installed, install modules in the default profile
-            if [[ "${REMOTE_CONTAINERS:-}" == true ]]; then
-                OPT_PROFILE=devcontainer
-                install_modules=("${PROFILE_DEVCONTAINER[@]}")
-            else
-                OPT_PROFILE=default
-                install_modules=("${PROFILE_DEFAULT[@]}")
-            fi
-        fi
-        ;;
-    *)
-        error "Unknown profile: ${OPT_PROFILE}"
-        return 1
-        ;;
-    esac
-
     if [[ -n "${OPT_PROFILE}" ]]; then
-        info "Profile: ${OPT_PROFILE}"
+        profiles+=("${OPT_PROFILE}")
+        install_modules+=("%${OPT_PROFILE}")
+    else
+        readarray -t profiles < <(list_installed_profiles)
+        if [[ "${#profiles[@]}" -gt 0 ]]; then
+            readarray -t update_modules < <(printf "%%%s\n" "${profiles[@]}")
+        else
+            profiles=("$(show_default_profile)")
+            readarray -t install_modules < <(printf "%%%s\n" "${profiles[@]}")
+        fi
     fi
 
+    info "Profiles: ${profiles[*]}"
+
     # update all installed modules
-    install_modules+=("${INSTALLED_MODULES[@]}")
+    update_modules+=("${INSTALLED_MODULES[@]}")
 
     # deduplicate and sort modules
     readarray -t install_modules < <(sort_uniq_args "${install_modules[@]}")
+    readarray -t update_modules < <(sort_uniq_args "${update_modules[@]}")
+
+    local -A handled_modules=()
 
     # install each modules
-    local module
-    for module in "${install_modules[@]}"; do
-        if [[ "${FLG_DRY_RUN}" -eq 1 ]]; then
-            info "Would install module: ${module}"
-        else
-            install_module "${module}"
+    local module_name
+    for module_name in "${install_modules[@]}"; do
+        if [[ -n "${handled_modules["${module_name}"]:-}" ]]; then
+            continue
+        fi
+        handled_modules["${module_name}"]=1
+
+        local modules
+        readarray -t modules < <(expand_profile "${module_name}")
+
+        local module
+        for module in "${modules[@]}"; do
+            if [[ -n "${handled_modules["${module}"]:-}" ]]; then
+                continue
+            fi
+            handled_modules["${module}"]=1
+
+            local display_module="${module_name}"
+            if [[ "${module_name}" =~ ^% ]]; then
+                display_module="${module} (${module_name:1})"
+            fi
+
+            if ! check_module_exists "${module}"; then
+                error "Module not found: ${display_module}"
+                return 1
+            fi
+
+            if [[ "${FLG_DRY_RUN}" -eq 1 ]]; then
+                info "Would install module: ${display_module}"
+            else
+                install_module "${module}"
+            fi
+        done
+
+        if [[ "${FLG_DRY_RUN}" -ne 1 ]] && [[ "${module_name}" =~ ^% ]]; then
+            add_to_installed_modules "${module_name}"
+        fi
+    done
+
+    # update each modules
+    local module_name
+    for module_name in "${update_modules[@]}"; do
+        if [[ -n "${handled_modules["${module_name}"]:-}" ]]; then
+            continue
+        fi
+
+        local modules
+        readarray -t modules < <(expand_profile "${module_name}")
+
+        local module
+        for module in "${modules[@]}"; do
+            if [[ -n "${handled_modules["${module}"]:-}" ]]; then
+                continue
+            fi
+            handled_modules["${module}"]=1
+
+            local display_module="${module_name}"
+            if [[ "${module_name}" =~ ^% ]]; then
+                display_module="${module} (${module_name:1})"
+            fi
+
+            if ! check_module_exists "${module}"; then
+                warn "Module not found: ${display_module}"
+                if [[ "${FLG_DRY_RUN}" -ne 1 ]]; then
+                    remove_from_installed_modules "${module}"
+                fi
+                continue
+            fi
+            if [[ "${FLG_DRY_RUN}" -eq 1 ]]; then
+                info "Would update module: ${display_module}"
+            else
+                install_module "${module}"
+            fi
+        done
+
+        if [[ "${FLG_DRY_RUN}" -ne 1 ]] && [[ "${module_name}" =~ ^% ]]; then
+            add_to_installed_modules "${module_name}"
         fi
     done
 }
